name:          Code Standards
description:   Standards for developing flexible, durable, and sustainable HTML and CSS.
url:           http://codeguide.co

permalink:     pretty
highlighter:   rouge

collections:
  html:
    order: 10
  css:
    order: 20
  javascript:
    order: 30
  php:
    order: 40
  sage:
    order: 50
  liquid:
    order: 60
  git:
    order: 70
collections_dir: standards

defaults:
  - scope:
      path: ""
      type: "html"
    values:
      topic: html
      language: html
  - scope:
      path: ""
      type: "css"
    values:
      topic: css
      language: scss
  - scope:
      path: ""
      type: "javascript"
    values:
      topic: javascript
      language: javascript
  - scope:
      path: ""
      type: "php"
    values:
      topic: php
      language: php
  - scope:
      path: ""
      type: "sage"
    values:
      topic: sage
      language: html
  - scope:
      path: ""
      type: "liquid"
    values:
      topic: liquid
      language: liquid
  - scope:
      path: ""
      type: "git"
    values:
      topic: git
      language: git