name:          Gearbox Code Standards
description:   Standards for developing flexible, durable, and sustainable HTML and CSS.
url:           http://codeguide.co

permalink:     pretty
pygments:      true